### ISSUE TITLE
[BUG] 无法运行

### ISSUE THREAD

**Issue by hhhhhge** [yzyyz1387/nonebot_plugin_admin#120]
**描述 bug**
无法运行

**如何复现**
1. 我安装并导入了插件
2. 在 xx 时候 xx 情况下，出现了 xx 问题

**报错截图 （python的报错请截最下面）**
04-13 13:00:02 [ERROR] nonebot | Failed to import "nonebot_plugin_admin"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/__init__.py", line 11, in <module>
    from . import (
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/admin.py", line 18, in <module>
    from .admin_role import DEPUTY_ADMIN
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/admin_role.py", line 13, in <module>
    from .approve import g_admin
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/approve.py", line 14, in <module>
    from .utils import json_load
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/utils.py", line 29, in <module>
    from .config import plugin_config, global_config
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/config.py", line 16, in <module>
    plugin_config = Config.parse_obj(global_config)
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/pydantic/main.py", line 1099, in parse_obj
    return cls.model_validate(obj)
  File "/home/orangepi/qqbot-adminmanager/.venv/lib/python3.10/site-packages/pydantic/main.py", line 532, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
  Input should be a valid dictionary or instance of Config [type=model_type, input_value=Config(driver='~fastapi',....timedelta(seconds=120)), input_type=Config]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type

**环境**
 - 操作系统 
 - Python 版本 
 - Nonebot2 版本号
 - 在那里下载的本插件
   - pypi (商店安装 或者 pip 安装（本质一样）)
   - github ( 说明分支 )

**其他内容**
...

**Comment by postyizhan** [comment]
![图片](https://github.com/yzyyz1387/nonebot_plugin_admin/assets/97342038/afeaaf70-c349-44ce-9822-7dcfb832b1c5)

**Comment by yzyyz1387** [comment]
@hhhhhge @postyizhan nb版本号发一下，刚才问了一下，现在nb不锁pyd版本，以至原插件pyd1读取配置的写法在你们的环境下会报错

**Comment by postyizhan** [comment]
那个。。怎么查看nb版本号

**Comment by hhhhhge** [comment]
> @hhhhhge @postyizhan nb版本号发一下，刚才问了一下，现在nb不锁pyd版本，以至原插件pyd1读取配置的写法在你们的环境下会报错

什么时候修好呢

**Comment by yzyyz1387** [comment]
[Nonebot2 配置](https://nonebot.dev/docs/appendices/config#%E9%85%8D%E7%BD%AE%E9%A1%B9%E7%9A%84%E5%8A%A0%E8%BD%BD)

**Comment by yzyyz1387** [comment]
> 那么我有用pydantic2的插件会不会不兼容

会

**Comment by hhhhhge** [comment]
那么作者是否可以更新一下呢

**Comment by ChiLinCN** [comment]
有测试过最新版包用什么版本的Pydantic可以运行吗 nonebot教程降级的版本还是会出现相同的状况
