### ISSUE TITLE
出现报错

### ISSUE THREAD

**Issue by HuYihe2008** [yzyyz1387/nonebot_plugin_admin#44]
```
08-25 10:50:33 [INFO] nonebot | Matcher <Matcher from src.plugins.nonebot_plugin_admin.auto_ban, type=message, priority=2, temp=False> running complete
08-25 10:50:33 [ERROR] nonebot | Running matcher <Matcher from src.plugins.nonebot_plugin_admin.auto_ban, type=message, priority=2, temp=False> failed.
Traceback (most recent call last):
File "/usr/local/bin/nb", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
run_bot(file, app)
File "/usr/local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
nonebot.run(app=f"{module_name}:{app}")
File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
get_driver().run(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
uvicorn.run(
File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 575, in run
server.run()
File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
return asyncio.run(self.serve(sockets=sockets))
File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
await matcher.run(bot, event, state, stack, dependency_cache)
File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
await self.simple_run(bot, event, state, stack, dependency_cache)
File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
await handler(
File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
return await self.call(**values)
File "/opt/jamyidobot/./src/plugins/nonebot_plugin_admin/auto_ban.py", line 35, in _
if rule[0] and re.search(rule[0], msg): # TODO: 分群配置
File "/usr/lib64/python3.9/re.py", line 201, in search
return _compile(pattern, flags).search(string)
File "/usr/lib64/python3.9/re.py", line 304, in _compile
p = sre_compile.compile(pattern, flags)
File "/usr/lib64/python3.9/sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "/usr/lib64/python3.9/sre_parse.py", line 948, in parse
p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
File "/usr/lib64/python3.9/sre_parse.py", line 443, in _parse_sub
itemsappend(_parse(source, state, verbose, nested + 1,
File "/usr/lib64/python3.9/sre_parse.py", line 671, in _parse
raise source.error("multiple repeat",
re.error: multiple repeat at position 2
```

是我的问题还是插件的问题😅

**Comment by yzyyz1387** [comment]
https://github.com/yzyyz1387/nonebot_plugin_admin/issues/22#issuecomment-1178801725

**Comment by yzyyz1387** [comment]
仓库里是开发中的版本，还有，block了
