### ISSUE TITLE
接受消息会报错Running matcher <Matcher from nonebot_plugin_admin.auto_ban, type=message, priority=0, temp=False> failed.，但是部分功能可以正常使用

### ISSUE THREAD

**Issue by leyandh** [yzyyz1387/nonebot_plugin_admin#55]
![image](https://user-images.githubusercontent.com/72337047/201506103-14ae754b-3359-4e75-bffe-a41b73272e45.png)

**Comment by yzyyz1387** [comment]
用新版

**Comment by leyandh** [comment]
谢谢，被困在学校了，没回复

**Comment by leyandh** [comment]
解决了

**Comment by kugelblyat** [comment]
朋友，请问是如何解决的这个问题，我也遇到了同样的问题

**Comment by leyandh** [comment]
> 朋友，请问是如何解决的这个问题，我也遇到了同样的问题

更新插件

**Comment by kugelblyat** [comment]
04-14 08:23:46 [ERROR] nonebot | Failed to import "nonebot_plugin_gpt3"
Traceback (most recent call last):
  File "D:\kugelblyat\mai-bot-main\bot.py", line 27, in <module>
    nonebot.load_plugin('nonebot_plugin_gpt3')
  File "C:\Users\admin\.conda\envs\kugel\lib\site-packages\nonebot\plugin\load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\admin\.conda\envs\kugel\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\admin\.conda\envs\kugel\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\admin\.conda\envs\kugel\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\admin\.conda\envs\kugel\lib\site-packages\nonebot_plugin_gpt3\__init__.py", line 7, in <module>
    from .config import *
  File "C:\Users\admin\.conda\envs\kugel\lib\site-packages\nonebot_plugin_gpt3\config.py", line 30, in <module>
    openai_api_key = config.openai_api_key
AttributeError: 'Config' object has no attribute 'openai_api_key'
这是现在它的报错，插件已经更新到了最新版本，这好像没有看到有人出同样的问题，昨天困扰我一天了
