### ISSUE TITLE
[BUG]无法初始化读取群号失败

### ISSUE THREAD

**Issue by Sincejunly** [yzyyz1387/nonebot_plugin_admin#60]
**描述 bug**
无法初始化

**如何复现**
1. 我通过文件夹载入方式安装并导入了插件
2. 在 今天时候 启动情况下，出现了 无法初始化问题

**报错截图 （python的报错请截最下面）**

```
12-13 02:14:56 [ERROR] nonebot | Failed to import "nonebot_plugin_admin"
Traceback (most recent call last):
  File "D:\NoneBot2\homura\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "D:\conda_data\envs\Python3.8.15\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\NoneBot2\homura\src\plugins\nonebot_plugin_admin\__init__.py", line 22, in <module>
    from . import (
  File "D:\NoneBot2\homura\src\plugins\nonebot_plugin_admin\approve.py", line 14, in <module>
    from .utils import load
  File "D:\NoneBot2\homura\src\plugins\nonebot_plugin_admin\utils.py", line 38, in <module>
    def At(data: str) -> Union[list[str], list[int], list]:
TypeError: 'type' object is not subscriptable

```
```
12-13 02:09:05 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "D:\NoneBot2\homura\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app")
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\conda_data\envs\Python3.8.15\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\conda_data\envs\Python3.8.15\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "D:\conda_data\envs\Python3.8.15\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\conda_data\envs\Python3.8.15\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "D:\conda_data\envs\Python3.8.15\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "D:\conda_data\envs\Python3.8.15\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
> File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\internal\driver\driver.py", line 146, in _run_hook
    await asyncio.gather(*coros)
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
    return await coro
  File "D:\conda_data\envs\Python3.8.15\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\NoneBot2\homura\src\plugins\nonebot_plugin_admin\config.py", line 22, in _
    await utils.init()
AttributeError: module 'src.plugins.nonebot_plugin_admin.utils' has no attribute 'init'
```

**环境**
 - windows 11 
 - Python 版本  略
 - Nonebot2 版本号 2.0.0r2
 - 在那里下载的本插件
   - github ( 基线 )

**其他内容**
...

**Comment by Sincejunly** [comment]
群号遵循send_group_id = ["xxxx"]格式

**Comment by yzyyz1387** [comment]
6

**Comment by Sincejunly** [comment]
你这个错误挺离谱的，我给你修了，散了

**Comment by yzyyz1387** [comment]
根据你的两段报错，第一段是nonebot-plugin-manager的历史遗留问题 [https://github.com/nonepkg/nonebot-plugin-manager/issues/11](https://github.com/nonepkg/nonebot-plugin-manager/issues/11)

**Comment by yzyyz1387** [comment]
> 你这个错误挺离谱的，我给你修了，散了

别开玩笑了哥

**Comment by Sincejunly** [comment]
> > 你这个错误挺离谱的，我给你修了，散了
> 
> 别开玩笑了哥

我已经加载成功了，有必要跟你开玩笑？

**Comment by Sincejunly** [comment]
> 想想为什么49条issue只有你出现这种问题

我只设了个群号别的没管

**Comment by Sincejunly** [comment]
> 想想为什么49条issue只有你出现这种问题

然而实际上就是我改了之后运行了，

**Comment by yzyyz1387** [comment]
可算看懂了，你说哪个什么send_group来自 #37 @GC-ZF ,请自行查阅 [https://github.com/yzyyz1387/nonebot_plugin_admin/pull/37/commits](https://github.com/yzyyz1387/nonebot_plugin_admin/pull/37/commits)

**Comment by Sincejunly** [comment]
> 想想为什么49条issue只有你出现这种问题

你搞得我都不自信了，再去翻翻你的说明 ，与其想你脑子里那套，不如接受现实如何，除非你说不兼容，但你好像没说

**Comment by yzyyz1387** [comment]
![image](https://user-images.githubusercontent.com/51691024/207126299-5fb54215-3899-42b0-aa7c-0589088bebf2.png)

**Comment by Sincejunly** [comment]
> ![image](https://user-images.githubusercontent.com/51691024/207126299-5fb54215-3899-42b0-aa7c-0589088bebf2.png)

有没有可能，我就没截图

**Comment by yzyyz1387** [comment]
![image](https://user-images.githubusercontent.com/51691024/207126471-b748c58c-6684-4d0a-b804-d719a9323bbd.png)
