### ISSUE TITLE
[BUG]导入插件报错

### ISSUE THREAD

**Issue by Cloudwhile** [yzyyz1387/nonebot_plugin_admin#72]
12-19 23:58:19 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_makemidi"
12-19 23:58:19 [ERROR] nonebot | Failed to import "nonebot_plugin_admin"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\python\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\python\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\bot\mcqq\mcqq_bot\bot.py", line 29, in <module>
    nonebot.load_plugin("nonebot_plugin_admin")
  File "C:\Program Files\python\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Program Files\python\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Program Files\python\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\python\lib\site-packages\nonebot_plugin_admin\__init__.py", line 22, in <module>
    from . import (
  File "C:\Program Files\python\lib\site-packages\nonebot_plugin_admin\approve.py", line 14, in <module>
    from .utils import load
  File "C:\Program Files\python\lib\site-packages\nonebot_plugin_admin\utils.py", line 38, in <module>
    def At(data: str) -> Union[list[str], list[int], list]:
TypeError: 'type' object is not subscriptable

系统版本和环境
win server 2019 python 3.8.6

**Comment by yzyyz1387** [comment]
从哪儿下的插件

**Comment by Cloudwhile** [comment]
pip


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月20日(周二) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yzyyz1387/nonebot_plugin_admin] [BUG]导入插件报错 (Issue #72)




 
从哪儿下的插件
 
&mdash;

**Comment by yzyyz1387** [comment]
拉仓库的版本用

**Comment by yzyyz1387** [comment]
### 为了让从pip下载的用户能够使用本插件，进行了[一次发版](https://github.com/yzyyz1387/nonebot_plugin_admin/actions/runs/3733273033)，
### 见 [releases](https://github.com/yzyyz1387/nonebot_plugin_admin/releases), 你可以从pip更新再试，由于迭代较快，很难保证以前的版本是否可用

**Comment by Cloudwhile** [comment]
还是不行？

**Comment by yzyyz1387** [comment]
![image](https://user-images.githubusercontent.com/51691024/208563665-2e68e9da-c937-4319-ad71-35b296e89300.png)

**Comment by Cloudwhile** [comment]
12-20 08:36:08 [ERROR] nonebot | Failed to import "nonebot_plugin_admin"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\python\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\python\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\bot\mcqq\mcqq_bot\bot.py", line 29, in <module>
    nonebot.load_plugin("nonebot_plugin_admin")
  File "C:\Program Files\python\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Program Files\python\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Program Files\python\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\python\lib\site-packages\nonebot_plugin_admin\__init__.py", line 11, in <module>
    from . import (
  File "C:\Program Files\python\lib\site-packages\nonebot_plugin_admin\admin.py", line 20, in <module>
    from .utils import At, MsgText, banSb, change_s_title, fi, log_fi, sd, Reply, log_sd
  File "C:\Program Files\python\lib\site-packages\nonebot_plugin_admin\utils.py", line 39, in <module>
    def At(data: str) -> Union[list[str], list[int], list]:
TypeError: 'type' object is not subscriptable

**Comment by Cloudwhile** [comment]
12-20 15:04:07 [ERROR] nonebot | Failed to import "nonebot_plugin_admin"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\bot\mcqq\mcqq_bot\bot.py", line 29, in <module>
    nonebot.load_plugin("nonebot_plugin_admin")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_admin\__init__.py", line 11, in <module>
    from . import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_admin\group_msg.py", line 62, in <module>
    send_sentence_morning = get_driver().config.send_sentence_morning
AttributeError: 'Config' object has no attribute 'send_sentence_morning'

**Comment by yzyyz1387** [comment]
请阅读README.md

**Comment by Cloudwhile** [comment]
![image](https://user-images.githubusercontent.com/86512509/208611906-75962ffe-dabb-4cf6-a6e9-38b04093d214.png)

**Comment by yzyyz1387** [comment]
请仔细阅读README.md
