### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sydrr0** [yzyyz1387/nonebot_plugin_admin#90]
**描述 bug**
救命啊，插件出现了无法加载json文件的问题

**如何复现**
1. 我通过 商店 方式安装并导入了插件

这里放截图，可使用任何截图工具截图，然后在这里按下 ** 07-30 12:11:50 [ERROR] nonebot | Failed to import "nonebot_plugin_admin"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/__init__.py", line 11, in <module>
    from . import (
  File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/broadcast.py", line 35, in <module>
    json_upload(broadcast_avoid_path, broadcast_config)
  File "/home/sydrro/daily/.venv/lib/python3.10/site-packages/nonebot_plugin_admin/utils.py", line 381, in json_upload
    with open(path, mode='w', encoding='utf-8') as c:
FileNotFoundError: [Errno 2] No such file or directory: 'config/广播排除群聊.json'**

**环境**
 - 操作系统 linux
 - Python 版本 3.10.6
 - Nonebot2 版本号 最新的
 - 在那里下载的本插件
    商店安装

**Comment by yzyyz1387** [comment]
问题#76，在 #80 已经修复，你插件是什么版本的，可以 `pip show nonebot-plugin-admin` 看看？

**Comment by Sydrr0** [comment]
> 问题#76，在 #80 已经修复，你插件是什么版本的，可以 `pip show nonebot-plugin-admin` 看看？

您好，我已经解决了谢谢！！

**Comment by yzyyz1387** [comment]
是手动建文件夹解决的么，按理来说应该不用这样，应该会自己创建的，你插件时最新版吗，如果最新版还存在这样的问题可能得修修，我很久没动代码了，抱歉给你带来了不好的体验，也感谢你使用我们的插件

**Comment by Sydrr0** [comment]
> 是手动建文件夹解决的么，按理来说应该不用这样，应该会自己创建的，你插件时最新版吗，如果最新版还存在这样的问题可能得修修，我很久没动代码了，抱歉给你带来了不好的体验，也感谢你使用我们的插件

您客气了，我是手动创建的，也是最新版本的，我昨天安装的时候确实不需要手动安装，今天重新刷了一下ubuntu sever，突然就出现了这个bug，只需要手动创建一个config文件夹即可了

**Comment by Sydrr0** [comment]
> 是手动建文件夹解决的么，按理来说应该不用这样，应该会自己创建的，你插件时最新版吗，如果最新版还存在这样的问题可能得修修，我很久没动代码了，抱歉给你带来了不好的体验，也感谢你使用我们的插件

直接商店指令安装的，是最新版把

**Comment by yzyyz1387** [comment]
是的，那你就觉了就好，我有时间看看吧
